### ISSUE TITLE
Data Updates [Epic 5 (Discovery)]

### ISSUE THREAD

**Issue by NEDJIMAbelgacem** [kartoza/rezoning-2-project#10]
Note that discovery tasks will be completed by order of priority in line with discovery task requirements[.](https://rezoning.energydata.info/) Discovery may include documentation and/ or implementation of feature design.
### Expectation: 
Update datasets with latest version.
### Priority: 
Various
### Dependencies:
None
### Description:
Update datasets with latest version (e.g LULC 2020 from ESA)
### Scope:
The scope of this process will depend on the results of the discovery process. As this task is multifaceted and applies to multiple datasets, it is expected to have a partial or incomplete processing and update status for some datasets.
### Requirements:
A list of expected (new and existing) data layers, and data processing pipeline details
### Success Criteria:
Updated data is available from the application, and data sources and requirements are effectively documented

**Comment by ClaraIV** [comment]
Datasets to update (so far):
-GADM 4.0
-ESA LULC 2021: https://worldcover2021.esa.int/

**Comment by NEDJIMAbelgacem** [comment]
The GADM dataset was updated to version 4.1 which contains more recent administrative regions for countries.

**Comment by ClaraIV** [comment]
an update on the LULC dataset please?

**Comment by LunaAsefaw** [comment]
@akshay2408 please see Clara's comment above
