### ISSUE TITLE
User Data Uploads [Epic 5 (Discovery)]

### ISSUE THREAD

**Issue by NEDJIMAbelgacem** [kartoza/rezoning-2-project#11]
Note that discovery tasks will be completed by order of priority in line with discovery task requirements[.](https://rezoning.energydata.info/) Discovery may include documentation and/ or implementation of feature design.
### Expectation:
Allow users to upload their own data sources
### Priority:
Medium
### Dependencies:
None
### Description:
Users should be able to provide data sources which can be used in the analysis and filtering operations, such as transmission lines etc.
### Scope:
The scope of this process will depend on the results of the discovery process.
### Out of scope:
This implementation is expected to be ephemeral and operate in a client side context, whereby no state is stored on the server or implementation of user accounts etc.
### Requirements:
None
### Success Criteria:
Users are able to effectively use ther own data inputs for analysis

**Comment by NEDJIMAbelgacem** [comment]
Hi @ClaraIV  @gclapp1 
I believe this ticket needs to be more clarified and split into different tickets according to your feedback.
I have done some thoughts about this one:
- What about the ability of using an area's boundaries provided by the user as a polygon: For a start the user can provide a geojson countaining boundaries of an area or multiple areas in one json file and the app will calculate the zone score, lcoe according to filters and weight... We can afterwards add UI for drawing a polygon on the map to avoid the necessity of having a geojson file (Although it will still be useful to have the area selection as a json file).
- I was thinking about where the layers you want to use are hosted exactly since layers are often huge in size and uploading a layer somewhere wouldn't be practical in most cases. If you have specific layers you want to use with rezoning let me know about them so I can assess how much work have to be done to achieve using these layers.

**Comment by ClaraIV** [comment]
this refers mainly to users having the option to upload their own transmission lines and run the analysis; therefore it's focused on light, vector files (perhaps we can limit it to just this one for now, to see how it goes) and the layer does not need to be stored; just used for that single run of the analysis to enable users to obtain more accurate results; We actually want to avoid to save/host any of the user data, as it is a complicated matter
