### ISSUE TITLE
Layer Consistency [Epic 5 (Discovery)]

### ISSUE THREAD

**Issue by NEDJIMAbelgacem** [kartoza/rezoning-2-project#13]
Note that discovery tasks will be completed by order of priority in line with discovery task requirements[.](https://rezoning.energydata.info/) Discovery may include documentation and/ or implementation of feature design.
### Expectation: 
The list of contextual layers should be the same as the layers in the filter tab for each
equation
### Priority: 
Low
### Dependencies: 
None
### Description: 
No extra layers (e.g. capacity factor) should be included, and the contextual and filter layers should remain consistent.
### Scope: 
The scope of this process will depend on the results of the discovery process.
### Requirements:
None
### Success Criteria: 
Available layers remain consistent between the filter tab and contextual layers

**Comment by NEDJIMAbelgacem** [comment]
This ticket is very related to interactive filtering.
Eventually the user will not need a contextual layers and that panel will be switched into something like "Output layers".

**Comment by NEDJIMAbelgacem** [comment]
This have been addressed by making the eye button to display the filter's layer. which meant there was no need for many layers to be in the contextual layers menu.
Let me know if this fixes the issue.

**Comment by ClaraIV** [comment]
This needs to be checked thoroughly for each layer as not all layers function properly, or at least not for all countries/regions. 
Eg., for Caspian Sea the UNESCO layer is activated and visible only upon "deactivation", and is not displayed when actually "Active" like the other layers.

![image](https://user-images.githubusercontent.com/9391517/233992726-990ac5f0-706b-401c-bd65-608d6691b909.png)

Not for all countries the vector symbols are displayed properly or even consistently, see below screenshot for Airports for Solar and then for Onshore Wind; and below for another instance where we actually have symbols.

![image](https://user-images.githubusercontent.com/9391517/233994128-ec745bf2-7bb7-42f7-9df1-be5faf82d90a.png)

![image](https://user-images.githubusercontent.com/9391517/233994252-d50127c0-f7e4-4102-997e-45640c654af1.png)

![image](https://user-images.githubusercontent.com/9391517/233994479-a0032ddb-4263-439c-9f06-5cf90218f18a.png)

**Comment by akshay2408** [comment]
Hi @ClaraIV and @dimasciput 
My debugging about this task is as follows :- 
When I select Azerbaijan country (solar PV, 25km grid) and UNESCO filter is ON, then we have the following cases on staging and development.

This is the staging url and its response is blank image.
https://cenpsr6h9g.execute-api.us-east-2.amazonaws.com/v1/layers/AZE/solar/unesco/7/80/48.png?colormap=viridis&f_unesco=1000,165570&offshore=false

This is the development url and it has response image.
https://d2b8erzy6y494p.cloudfront.net/v1/layers/AZE/solar/unesco/7/80/48.png?colormap=viridis&f_unesco=1000,165570&offshore=false

Which means the data is not consistent on development and staging, I think we have different host and the s3 buckets in different region OR the buckets are not synced.
