### ISSUE TITLE
Regions: Caspian Sea and Black Sea  

### ISSUE THREAD

**Issue by gclapp1** [kartoza/rezoning-2-project#15]
1. The regions "Caspian Sea" and "Black Sea" which were originally made for Offshore show results for Solar and Wind as well

2. If users select a region, the resource map is not clipped to that region but is a global layer

**Comment by timlinux** [comment]
We should only be able to run offshore wind for these two regions

**Comment by NEDJIMAbelgacem** [comment]
Addressed in https://github.com/worldbank/WB-rezoning-explorer/pull/6
