### ISSUE TITLE
Countries removed from V1.0

### ISSUE THREAD

**Issue by gclapp1** [kartoza/rezoning-2-project#16]
USA and some countries/islands that were in REZoning 1.0 have been removed and are not selections in the current web application

**Comment by timlinux** [comment]
@NEDJIMAbelgacem if you size it to 20 then you must please make smaller linked tickets which break it down into tasks of max 1 day each.

**Comment by ClaraIV** [comment]
Kiribati is missing - it's in the country list but the map doesnt center on it, there is no boundaries shapefile; Does Marshall Islands have a shapefile? It doesnt show on the map;
Also, do you have the list of all countries that were added? I know we had a list somewhere but I cannot find it anymore, thanks!

**Comment by NEDJIMAbelgacem** [comment]
https://github.com/worldbank/WB-rezoning-explorer/pull/9/commits/b253587811c828b1d67e13ba0c08c7bae1042825

**Comment by ClaraIV** [comment]
is there an update for this ticket? Just checked and SUA, Russia and other countries are still missing

**Comment by dimasciput** [comment]
@akshay2408 can you test this ticket on staging?

**Comment by ClaraIV** [comment]
@dimasciput Kosovo is missing -can you please investigate?

**Comment by LunaAsefaw** [comment]
When looking at the list of countries listed under 12.1 of the Rezoning User Guide, the following countries (from IRENA Resources) are missing on the staging site:
Ashmore and Cartier Islands (Aus.)
Baker Island (U.S.)
Brunei Darussalam
Cabo Verde (Unless this is renamed to Cape Verde)
Clipperton Island (Fr.)
West Bank and Gaza 
Vatican City
Howland Island (U.S.)
Jarvis Island (U.S.)
Johnston Atoll (U.S.)
Kingman Reef (U.S.) 
Madeira Islands (Por.) 
Midway Island (U.S.) 
Navassa Island (U.S.) 
Palmyra Atoll (U.S.) 
Wake Island (U.S.)
Azores Islands (Por.)
Kosovo
Bonaire (Neth.)
Saba (Neth.)
Sint Eustatius (Neth.) 
Sovereign Base Areas of Akrotiri 
and Dhekelia (U.K.)
Abyei

**Comment by akshay2408** [comment]
Hi @ClaraIV @LunaAsefaw  This is list of territory i checked in the code we have list of Countries and when i try to add above list and the country list the code is breaking so. i am trying to figure it out

**Comment by LunaAsefaw** [comment]
Closing this to have a single source focusing on the issue of missing countries. Please use #63
