### ISSUE TITLE
Investigate Timeout Responses

### ISSUE THREAD

**Issue by gclapp1** [kartoza/rezoning-2-project#17]
Maldives, Cocos Islands and likely others do not generate zones or even parameters/boundaries for any selection of RE (offshore, onshore, solar)

**Comment by NEDJIMAbelgacem** [comment]
This is caused mainly because there is no entry of the AOI in rezoning_api/db/countries.geojson for Cocos Islands. It could potentially be a matter of just adding a gemetry to that file or something else

**Comment by NEDJIMAbelgacem** [comment]
Partially addressed by https://github.com/worldbank/WB-rezoning-explorer/pull/3 for some countries.
Some countries (like Cocos Islands) cause internal server error that is caused by the AOI of the country not existing inside rezoning_api/db/countries.geojson .

**Comment by ClaraIV** [comment]
I am not sure what the conclusion/ solution is for this ticket -> all the countries above still don't generate any results, can you explain what has been done to address this?

**Comment by LunaAsefaw** [comment]
US and Russia were some of the countries that used to generate a timeout response but they currently generate outputs without crashing the site

![Image](https://github.com/kartoza/rezoning-2-project/assets/90245715/f20b1132-817c-42c4-b057-408a26807909)


![Image](https://github.com/kartoza/rezoning-2-project/assets/90245715/6377b759-8a3e-4d01-a58e-cb3028d6b945)

**Comment by gclapp1** [comment]
Timeout Response issue no longer occurring for initial countries, Russia, U.S or random selection of test countries with diferent sizes and parameters, closing ticket.
