### ISSUE TITLE
Export Updates (2/3) - Invalid spatial files

### ISSUE THREAD

**Issue by gclapp1** [kartoza/rezoning-2-project#25]
Export of spatial files (tifs) results in invalid files (infinite values)->See Cabo Verde for example

**Comment by NEDJIMAbelgacem** [comment]
https://github.com/worldbank/WB-rezoning-explorer-api/pull/1

**Comment by gclapp1** [comment]
For both the LCOE and Score GeoTIFF file downloads on the staging site I receive the following messages: 

![Image](https://user-images.githubusercontent.com/57463392/211575021-601196f1-56aa-47cf-aa77-3a0b5ba34ca0.png)

**Comment by NEDJIMAbelgacem** [comment]
> For both the LCOE and Score GeoTIFF file downloads on the staging site I receive the following messages:
> 
> ![Image](https://user-images.githubusercontent.com/57463392/211575021-601196f1-56aa-47cf-aa77-3a0b5ba34ca0.png)

Hi @ClaraIV , I noticed that the exporting is not working on the staging website unfortunately and I'm communicating with Derilinx to fix that ASAP.

**Comment by ClaraIV** [comment]
I need more time to investigate this, as I am unsure on the values produced; please let's keep the ticket open for now

**Comment by ClaraIV** [comment]
I tested Cape Verde and I cannot open the following spatial outputs - > they are not displayed in QGIS.
Other countries I tested work fine, but the ones that had issues before still present them, e.g: Cape Verde, 
Furthermore, I can't seem to be able to export in CSV format at all. @NEDJIMAbelgacem please test the files in a GIS software during the internal testing to ensure that everything is displayed properly- returning this ticket for further revisions.

![image](https://user-images.githubusercontent.com/9391517/233367638-1e39a065-63cc-42dd-84a9-04b80e29110d.png)

**Comment by dimasciput** [comment]
@akshay2408 please test this ticket

**Comment by dimasciput** [comment]
> Furthermore, I can't seem to be able to export in CSV format at all.

This is fixed and deployed to staging.

**Comment by LunaAsefaw** [comment]
@ClaraIV @gclapp1 I was able to download the csv and load the raster and geojson file in QGIS. I am concerned about the values returned though. Is the range given for the raster files as expected? I know it ranges from 0-1 on the site but the range is different on QGIS, is this correct?
![image](https://github.com/kartoza/rezoning-2-project/assets/90245715/50490a2e-5023-44a4-8acf-3dc7932cef48)

**Comment by ClaraIV** [comment]
I also dont understand this new range of values, the first example looks fine to me but not the 2nd one; I would recommend that you compare results for the same country with the published tool; I believe these new values are a result of Belgacem trying to fix the invalid files, but they dont seem right

**Comment by LunaAsefaw** [comment]
@dimasciput @akshay2408 Cape Verde results in invalid files, both the geojson and TIFF files. The layers load on QGIS but nothing is displayed (even after clicking 'zoom to layer' in case it is a projection issue) 
![image](https://github.com/kartoza/rezoning-2-project/assets/90245715/e3b65e8a-27d5-4cb9-8b3a-3c8b4dee1c48)

**Comment by gclapp1** [comment]
Cape Verde TIF and GeoJSON files downloaded from REZoning both load into QGIS with appropriate displays and attribute tables.
