### ISSUE TITLE
Some inconsistencies between the front end and backend countries

### ISSUE THREAD

**Issue by NEDJIMAbelgacem** [kartoza/rezoning-2-project#27]
Some countries like Cocs islands exists in the frontend but there is no areas for this in the backend (rezoning_api/db/countries.json).
The geometries for these countries need to be added to the backend

**Comment by ClaraIV** [comment]
I dont see any geometry for Cocos Island and I couldnt run the tool regardless of aggregation method selected

**Comment by dimasciput** [comment]
@akshay2408 please can you check this?

**Comment by LunaAsefaw** [comment]
All the countries on the site have geometry files in the backend. See WB-Explorer>app>public>zones>countries
