### ISSUE TITLE
Analysis is NULL if one layer is missing

### ISSUE THREAD

**Issue by ClaraIV** [kartoza/rezoning-2-project#31]
tool does not yield results if a layer is missing; for example: if there is no transmission grid for a country (Fiji) we cannot run the tool; can we "skip" the layers that are absent and still run the analysis? perhaps give a warning signal of the layers that are missing, so that the user knows the limitations for that specific country?

**Comment by NEDJIMAbelgacem** [comment]
Hi @ClaraIV ,
I think from the backend's standpoint we can't be sure whether a certain area does not contain data in apecific layer (transmission lines for example). I can think of a good approach for this: Can we add toggle buttons for activating and deactivating filters (The default for this will be to make all filters activated)? If the app yields no results for a country or an area, this means that the filters are too restrictive and we then display a message in the UI of the zone results saying that all the areas were filtered out and you need to disable some filters.

**Comment by ClaraIV** [comment]
I think this is a good idea! however, we need to see for which filters we can add a "deactivate" button so that the computation formula still works, there must be filters which are absolutely mandatory for the tool to generate results

**Comment by NEDJIMAbelgacem** [comment]
Hi @ClaraIV 
 I made a PR for this here:
 https://github.com/worldbank/WB-rezoning-explorer/pull/10
 Let me know what you think

**Comment by ClaraIV** [comment]
looking forward to the final proposal from your side on how it should look, color wise and font wise etc. as per the team discussion last week

**Comment by NEDJIMAbelgacem** [comment]
Hi @ClaraIV 
As it is now on staging, when there are no suitable areas (Regardless whether it is from a missing layer or one filter responsible for filtering out the whole area of the country), a message is shown to the user telling him to adjust his parameters.
In the case of a missing layer, using the interactive filtering we can know if the layer doesn't exit or everything is filtered out. If the user wants to discard a filter and not filter out areas based on it, there is a deactivate toggle for that.
Feel free to test this workflow on staging and let me know your feedback

**Comment by ClaraIV** [comment]
![image](https://user-images.githubusercontent.com/9391517/236498097-f6fbb560-f1ca-406f-ae98-64bb6480ad37.png)

**Comment by dimasciput** [comment]
Hi @ClaraIV , do you want to remove the warning completely?

**Comment by LunaAsefaw** [comment]
@dimasciput I think Clara is making reference to issue #43, the caps still exist in the error message and the image is broken and it is not aligned on top of the error message and centered horizontally. If I am not mistaken, it should look like this, right @ClaraIV 

![image](https://github.com/kartoza/rezoning-2-project/assets/90245715/c46e9e05-5ee8-41ca-b869-5522c5a4b657)

**Comment by ClaraIV** [comment]
Yes!
