### ISSUE TITLE
Offshore Wind Layers are not clipped to country border

### ISSUE THREAD

**Issue by NEDJIMAbelgacem** [kartoza/rezoning-2-project#40]

**Comment by ClaraIV** [comment]
one obvious consequence of this is the results of analysis for Offshore Wind, which shows suitable areas on land. see below an example.

**Comment by NEDJIMAbelgacem** [comment]
Hi @ClaraIV this issue is fixed and now everything is clipped properly:

![Image](https://user-images.githubusercontent.com/29183781/229761086-849befec-3a6c-432e-91cb-3d71b1770a2b.png)

Also as it turns out this might have had some effect on the calculation results because the calculations on a zone before were done on the convex hull of the area's polygon not on the polygon itself which resulted in some extra data being accounted for that doesn't belong to the area.

**Comment by timlinux** [comment]
@NEDJIMAbelgacem to ensure land pixels are masked out

**Comment by timlinux** [comment]
Specific issues identified:

* Caspian not delivering results
* Cape Verde - overlaps land
* Chile not delivering results

Luna to work through each and compile a list of issue areas.

**Comment by NEDJIMAbelgacem** [comment]
For the countries that are not delivering results: Chile and Caspian sea, it is the filters filter out all the areas because of a likely missing layer's data

**Comment by NEDJIMAbelgacem** [comment]
I created a new ticket for the pixel level clipping as this ticket is actually fixed for larger areas:
https://github.com/kartoza/rezoning-2-project/issues/56

**Comment by ClaraIV** [comment]
It would be good to be sure, and not operate on guesses. Does the original
tool show results for these 2 areas? Please always compare with original
tool results

**Comment by akshay2408** [comment]
Hi @ClaraIV 
I have read the comments but could you please conclude what I have to do in this tickets.
I saw belgacem created one more ticket #56.

**Comment by ClaraIV** [comment]
Hi @akshay2408 if it;s not clear from the comments I dont think I can help further through additional comments, let us discuss in our meeting; please focus on other tickets until then - thanks!

**Comment by LunaAsefaw** [comment]
Hi @ClaraIV 
When I increase the anchorage distance to the full range, we also get results on the staging site, so the only reason the production site generates results but the staging site did not is due to the default values being different, would you like us to change the default values in this situation?

![Image](https://github.com/kartoza/rezoning-2-project/assets/90245715/cf0cf0a0-e0d8-4bc7-b368-dcd8f76b43bf)

**Comment by ClaraIV** [comment]
hi Luna, thanks for catching this - the default values should be identical on the deployed site and the staging site, not sure how/why they changed - please double check that the default values from the deployed site are reflected 100% in the staging site - those were chosen after consultations with experts from all 3 sectors. Thanks!

**Comment by gclapp1** [comment]
Tested and findings were in-line with what was discussed in last week's meeting: some of the off-shore value ranges on the deployed site are higher or lower due to improper clipping of countries and regions. 

Thanks, closing ticket
