### ISSUE TITLE
Strange artifacts in Angola

### ISSUE THREAD

**Issue by timlinux** [kartoza/rezoning-2-project#41]
Staging -> Angola -> Offshore Wind

![image](https://user-images.githubusercontent.com/178003/220369718-9fc09c78-38bf-4a13-973c-02f9ef12f391.png)

Production -> Angola -> Offshore Wind

![image](https://user-images.githubusercontent.com/178003/220370576-05ea19ad-43ae-469d-8d4b-d995cb353865.png)

**Comment by ClaraIV** [comment]
this is still wrong on staging, see pic below;

![image](https://user-images.githubusercontent.com/9391517/225664038-6f949030-29b0-4fca-bf57-67499c01cb6c.png)

**Comment by NEDJIMAbelgacem** [comment]
> this is still wrong on staging, see pic below;
> 
> ![image](https://user-images.githubusercontent.com/9391517/225664038-6f949030-29b0-4fca-bf57-67499c01cb6c.png)

Actually that's just the filtering, if you press the blue toggle to the side of the view icon you will be able to deactivate the filtering and show the whole area for that filter.

**Comment by ClaraIV** [comment]
I haven't noticed display issues with any other countries, will move this to <Accepted>

The resource layers are loading extremely slow (or not at all, requiring a refresh of the page) but this is another issue that I am looking forward to discuss in today's meeting.
