### ISSUE TITLE
We need to unify the country lists between the backend and frontend 

### ISSUE THREAD

**Issue by timlinux** [kartoza/rezoning-2-project#42]
See #16 too.

We should use the same description format and if possible share the same description file.

**Comment by akshay2408** [comment]
I saw the changes of this PR but  some countries  are not visible on staging but i did  same changes on my local, same countries are visible on local

**Comment by LunaAsefaw** [comment]
All the countries on the site have geometry files in the backend. See WB-Explorer>app>public>zones>countries. All the missing countries in #16 have also been added
