### ISSUE TITLE
Move export and import to the top of the panel

### ISSUE THREAD

**Issue by timlinux** [kartoza/rezoning-2-project#45]
They should remain permanently visible on the screen when you scroll.

**Comment by NEDJIMAbelgacem** [comment]
The export parameters button has been moved to top and when it is clicked it will download 3 csv files representing the input of the app:
![export-parameters](https://user-images.githubusercontent.com/29183781/225003557-98def173-1abe-46c5-ac93-70377b04e812.png)

**Comment by timlinux** [comment]
Nice now we need to be able to import those files back to restore the state

**Comment by ClaraIV** [comment]
nice! can we reduce the size of the font to something smaller than the <Reset> and <Generate Zones> buttons? 
We could also just leave <symbol>Export and then add a new button <symbol>Import next to it, to save space

**Comment by timlinux** [comment]
Duplicates #50 ?

**Comment by timlinux** [comment]
@ClaraIV in the ticket title we suggest to move it to the top of the panel, but I think it works well at the bottom but fixed so it does not scroll away. Should we close this and keep it at the bottom? The importer is coming in issue #50

**Comment by ClaraIV** [comment]
yes

**Comment by timlinux** [comment]
Shrink buttons by changing text to 'Import' and 'Export' only with icon on left

Export needs an icon.

![Image](https://user-images.githubusercontent.com/178003/230097113-16771404-b6fd-429b-b77c-695a9f4742cc.png)

Also swap order of the icons

**Comment by timlinux** [comment]
Also, change behavior to just download/upload the CSV for the active panel. So when economics is selected you get teh export for the economics settings only etc.

**Comment by NEDJIMAbelgacem** [comment]
The icons and the heights are now update:
![icon update](https://user-images.githubusercontent.com/29183781/230354349-92633740-c353-4347-96c8-0f749ea2336c.png)
The behaviour is to download the selected panel's parameters now too

**Comment by ClaraIV** [comment]
Will test this when tool works; as per Tim's suggestion last week, please reorder the items to start with Export and then Import

**Comment by ClaraIV** [comment]
is it possible to keep, in the .csv, the same order for the parameters as they are in the tool? Wind Speed/ Bathymetry, etc.?

**Comment by ClaraIV** [comment]
also, please ensure only the filters specific to the analysis we run (solar, wind, offshore) are exported - thanks!

**Comment by akshay2408** [comment]
@NEDJIMAbelgacem this is the PR for this task https://github.com/worldbank/WB-rezoning-explorer/pull/23

**Comment by LunaAsefaw** [comment]
@dimasciput @akshay2408 please reorder the export and import buttons such that it starts with Export then Import as suggested by Tim and Clara
