### ISSUE TITLE
BUG when running tool

### ISSUE THREAD

**Issue by ClaraIV** [kartoza/rezoning-2-project#48]
There is an issue when running the tool, not sure what changes happened. The tool seems to not account for some of the spatial filters.

- please see result with running the tool on staging env for Cape Verde:

![Image](https://user-images.githubusercontent.com/9391517/225672272-95e5fe6c-5957-4c95-8dbd-02aa7ef89f6b.png)

- the exact same parameters when running the same analysis on the published tool:

![Image](https://user-images.githubusercontent.com/9391517/225672394-ec4223d4-06b2-4ee1-afb6-3cd959d60b21.png)

**Comment by ClaraIV** [comment]
sure: this is the published tool Home — REZoning Web (energydata.info)
<https://rezoning.energydata.info/>
Don't you have access to the original code anymore? I believe that
everything you change should be compared and double-checked against the
original setting, to avoid errors.

**Comment by NEDJIMAbelgacem** [comment]
Hi @ClaraIV this bug is fixed and you can check it on staging

**Comment by ClaraIV** [comment]
I cannot replicate the issue, therefore I will move this to <Accepted by ESMAP>
