### ISSUE TITLE
BUG on TOOL run (Boundaries)

### ISSUE THREAD

**Issue by ClaraIV** [kartoza/rezoning-2-project#49]
The tool should show the number of admin regions upon processing, not sure what this huge number is. See below original tool. \

(Also, the entire country is a result, the spatial filtering doesnt work anymore.)

![Image](https://user-images.githubusercontent.com/9391517/225685093-45e5bf74-1313-4d85-9655-54d01b74bbef.png)

![Image](https://user-images.githubusercontent.com/9391517/225685348-6c6aa514-fd7c-49a2-a6ba-4b197345a77c.png)

**Comment by ClaraIV** [comment]
It seems that the <Boundaries> selection does not apply to the Zone Score, as it should - but only to the suitable areas;
The zone score is computed in 25km2 grid - please correct and make sure this is reflected properly also in the exported outputs



![Image](https://user-images.githubusercontent.com/9391517/225686346-6175eb10-b51d-43d3-b95a-efd1d70f4c6e.png)

**Comment by NEDJIMAbelgacem** [comment]
I fixed this and it the app is working on staging without this bug

**Comment by ClaraIV** [comment]
Perhaps this image is better suited here; it seems there is still a bug with this feature, please see below.

I was testing another ticket for Aruba, and the below happened: I got an error message of NO Zones even if I have suitable areas in the country.
If you want to try to replicate the error:

select Aruba, Solar and country borders -> run tool -> suitable areas and 1 zone appears
change selection to 25km2 grid and re-run tool -> this happens

![image](https://user-images.githubusercontent.com/9391517/232783424-ee70d87e-e945-453a-b7c1-b04b2e2c7a96.png)

**Comment by akshay2408** [comment]
Hi @ClaraIV and @NEDJIMAbelgacem 
I checked this and found that there is no data in case of ARUBA country, I checked for AFGHANISTAN with the same paraemters.(You can check the data using the below links.)
https://gre.staging.derilinx.com/public/zones/country/AFG.topojson
https://gre.staging.derilinx.com/public/zones/country/ABW.topojson

**Comment by dimasciput** [comment]
Hi @ClaraIV, what do you think about this ticket? I think it's more of a data issue rather than a bug.

**Comment by ClaraIV** [comment]
hi @dimasciput , why do you think it is a data issue?
I checked and saw that all the layers have data for Aruba, you can double-check that in the tool itself.
It is surely a bug, regardless of data/no-data because if there would be no data, then there would be no resulting zones; the tool returns both results (the pink areas) and the warning sign that there is no data, therefore this needs to be investigated and fixed.

**Comment by dimasciput** [comment]
Hi @ClaraIV , thank you for the input, we will investigate this further.

**Comment by LunaAsefaw** [comment]
The issue of no zone being generated is under #70. The bug on tool run issue is resolved and the count that happens when the tool is ran reflects the admin regions count
