### ISSUE TITLE
Grid/ Boundary Selection [Epic 3]

### ISSUE THREAD

**Issue by NEDJIMAbelgacem** [kartoza/rezoning-2-project#5]
![grid-selection](https://user-images.githubusercontent.com/29183781/203069375-b22428ae-dca2-4fd3-b7e8-9cb318637026.png)

### Expectation: 
Allow users to select between grid/boundary after the selection of the resource, in a separate pop-up panel.
### Dependencies:
None
### Description:
When initiating the application, the interface prompts users to select a country in a pop-up panel (modal window). Once a country is selected, the user is then prompted in a new modal for resource selections. It is desired that this process be extended to allow users to specify whether they wish to restrict the current operation to the grid or boundary definition in a pop-up window.
### Scope:
This task will create a new modal window with two buttons that allow the state definition in a manner that is a replication of the functionality in the existing filtering options.
### Out of scope:
Modification to the existing filters or interfaces.
### Requirements:
None
### Success Criteria:
A third pop-up window for grid or boundary selection when initiating the application

**Comment by NEDJIMAbelgacem** [comment]
Addressed in https://github.com/worldbank/WB-rezoning-explorer/pull/2  
Ping @ClaraIV & @gclapp1 let me know your feedback

**Comment by gclapp1** [comment]
Instead of two buttons, in my computer's UI, I see three-screenshot included below. The same interface appears for on-shore wind, solar and off-shore wind.

![Image](https://user-images.githubusercontent.com/57463392/211570949-76e6ec24-1a2e-4f75-bb97-82ce497ed246.png)

**Comment by NEDJIMAbelgacem** [comment]
Hi @ClaraIV , 
Do u want it to be the UI to be the same as before but with the pop up of the resource selection panel?
![grid-admin-reg](https://user-images.githubusercontent.com/29183781/211578452-7fba9507-0c57-44c8-9cfe-25fc591c702b.png)

**Comment by NEDJIMAbelgacem** [comment]
Hi @ClaraIV 
I made sure that the boundaries option is not selectible for offshore resource last week (it is on staging also). Let me know if I need to change anything.

**Comment by ClaraIV** [comment]
looks good to me!

**Comment by ClaraIV** [comment]
@akshay2408 @dimasciput 
There is a bug related to this ticket that I just discovered. Offshore Wind should not allow the selection "boundaries".
However, when you select a country -> solar/wind-> boundaries and then change the technology to "offshore wind", the area of analysis does not change and you can run the tool with "offshore wind" - "boundaries" which runs in an infinity loop.
This shouldn't be allowed and the area of analysis should automatically change to either grid size



![Image](https://user-images.githubusercontent.com/9391517/236494261-292e61a4-978e-4b37-b0a0-dea000ed2f2e.png)

**Comment by akshay2408** [comment]
Okay @ClaraIV 
got it, I will work on it.

**Comment by ClaraIV** [comment]
awesome! thanks!
