### ISSUE TITLE
Import csv files

### ISSUE THREAD

**Issue by akshay2408** [kartoza/rezoning-2-project#51]
This is subtask 1 of #50 
 import one or multiple csv files for filters

**Comment by ClaraIV** [comment]
@LunaAsefaw  the import files seems to work fine:
-it changes the resource type and unit of analysis size properly, for the selected country; please refer to issue #68 for comment on turbine type imports and grateful if you could check the other parameters to ensure everything is updated properly

**Comment by LunaAsefaw** [comment]
100%, I have updated Akshay on the matter and will test it after the changes. Thanks @ClaraIV

**Comment by LunaAsefaw** [comment]
Importing csv does not work when the grid type is 'Boundaries' for all the countries.  @dimasciput 

![Image](https://github.com/kartoza/rezoning-2-project/assets/90245715/66835634-4044-4e03-bf98-523d0d58b1e0)
