### ISSUE TITLE
Feedback form improvements

### ISSUE THREAD

**Issue by timlinux** [kartoza/rezoning-2-project#54]
Remove the shading on the hide button

![Image](https://user-images.githubusercontent.com/178003/230090402-d64c048d-b31e-48c9-b572-91ad071bdb84.png)

Scroll to the panel bottom on  opening of the ticket form

**Comment by timlinux** [comment]
Use proper visual metaphor for button (blue background, white text)

![Image](https://user-images.githubusercontent.com/178003/230092181-864d02ae-2cdd-42db-aadf-f8b78a612994.png)

**Comment by akshay2408** [comment]
@NEDJIMAbelgacem this is PR for this task https://github.com/worldbank/WB-rezoning-explorer/pull/16
