### ISSUE TITLE
Pixel clipping

### ISSUE THREAD

**Issue by NEDJIMAbelgacem** [kartoza/rezoning-2-project#56]
Ensure that pixel are clipped properly withing the AOI

**Comment by akshay2408** [comment]
Hi @ClaraIV 
Please add some description. I'm not getting the requirement of this ticket.

**Comment by ClaraIV** [comment]
@akshay2408 please check the linked ticket for additional information: https://github.com/kartoza/rezoning-2-project/issues/40

**Comment by gclapp1** [comment]
Closed in alignment with #40
