### ISSUE TITLE
LCOE legend

### ISSUE THREAD

**Issue by ClaraIV** [kartoza/rezoning-2-project#57]
LCOE values are not reflected in LCOE legend -> no variation in pixel coloring on the map

![Image](https://user-images.githubusercontent.com/9391517/230888150-e83edb5c-35ef-4bf2-9e58-66ae08deab86.png)

**Comment by NEDJIMAbelgacem** [comment]
Actually this problem wasn't from the legend itself but because for LCOE layer we have a fixed range for values [80, 300] and with that range in some cases no (or more accurately too little) color variation show up on the map.
This issue has been fixed
Before:
![lcoe-before](https://user-images.githubusercontent.com/29183781/231829430-98d0edb5-2eb5-4727-b314-afc0367887e1.png)
After:
![lcoe-updated](https://user-images.githubusercontent.com/29183781/231829481-8f6681e4-2b66-443d-9a24-89396ef1fec7.png)

**Comment by ClaraIV** [comment]
nicely done!
I've tested it for couple countries and it looks good!
One thing I noticed for Offshore Wind is that the layer is under the EEZ layer, making it hard to see; can you move it on top of all other layers?

![image](https://user-images.githubusercontent.com/9391517/232807635-2f3b42d6-b589-4546-a713-9c2ee6015156.png)

**Comment by ClaraIV** [comment]
@akshay2048

**Comment by ClaraIV** [comment]
hi Akshay, I also included a screenshot - is that not visible? It shows exactly what I expressed in writing. You can also test it yourself -> run the tool for a country for Offshore and (for comparison) for Onshore and compare the result in display for the LCOE layer. 
You can also compare the 2 screenshots in my message and Belgacem's message above and notice the difference in the display of the layer, which make the difference very obvious..

**Comment by ClaraIV** [comment]
@akshay2408 , i simply asked for a change in the order of the spatial layers overlay, meaning to display first the LCOE layer on top of the EEZ border (the transparent polygon) so that it looks similar to the other technologies. This doesnt look good, there is no variation in the LCOE layer color at all, please revert all changes to what Belgacem implemented for the LCOE layer and simply focus on the drawing order of the files

**Comment by akshay2408** [comment]
okay @ClaraIV 
I have not deployed these changes to staging.
They are only in my local machine, so I will do the suggested changes.

**Comment by akshay2408** [comment]
@dimasciput Please review this PR https://github.com/worldbank/WB-rezoning-explorer/pull/27

**Comment by akshay2408** [comment]
Hi @ClaraIV 
here is the updated UI 
<img width="1270" alt="Screenshot 2023-05-02 at 12 44 41 PM" src="https://user-images.githubusercontent.com/11027786/235603364-ab923f07-bd63-4e21-b301-cdb44572ed02.png">

**Comment by ClaraIV** [comment]
thanks, this works well!
