### ISSUE TITLE
Legend Panel - reorganize

### ISSUE THREAD

**Issue by ClaraIV** [kartoza/rezoning-2-project#58]
As a result of the new Interactive Filtering feature, the Legend panel needs to be reorganized:
-remove the subcategories
-order of items: "Satellite Basemap" | Suitable Areas | LCOE | Zone Score | all the other layers

![Image](https://user-images.githubusercontent.com/9391517/230888616-a1329de7-f9b2-4b2e-90d1-79d25e0107db.png)

**Comment by akshay2408** [comment]
@NEDJIMAbelgacem this is the PR for this Task https://github.com/worldbank/WB-rezoning-explorer/pull/18
