### ISSUE TITLE
Clip Vectors [Epic 4]

### ISSUE THREAD

**Issue by NEDJIMAbelgacem** [kartoza/rezoning-2-project#6]
### Expectation: 
Clip vector layers to the AOI.
### Dependencies: 
None
### Description: 
The existing views include vector data such as roads that extend beyond the scope of the current boundary region. It is necessary to clip or mask such vector features so they are not visible.
### Scope:
The optimal process may depend on existing implementation details.
### Requirements:
Data processing pipeline details and access to vector source processes
### Success Criteria:
Vector features are visibly limited in extent to the selected regional boundaries

**Comment by NEDJIMAbelgacem** [comment]
# UPDATE:
This problem is caused by the frontend requesting vector tiles from rezoning vector tiles server without specifying the bounds of the area of interest. 
- Tried to lookup how to make mapbox clip the layer requested but seems like there is no option to do so for vector layers.

**Comment by ClaraIV** [comment]
Did you find any solution for <masking> instead? Adding a transparency level to the files outside the AOI?

**Comment by NEDJIMAbelgacem** [comment]
This has been implemented but I still have to switch to new mbtiles files.
The mbtiles needed additional attributes about the country they're in (each line needed that). I made a script to add that based on the intersection of the geometry of countries and said line. 
Since these mbtile files are probably shared between the staging and the production I opted to coordinate with Derilinx to upgrade to new files. Should be done by the end of this week!

**Comment by ClaraIV** [comment]
@akshay2408 this has not been implemented, I am moving it to <to do>

**Comment by gclapp1** [comment]
Unfortunately it appears that the vector features are not visibly limited to the selected regional boundaries and that Roads and Transmission lines still appear. 

For interconnection considerations this may be fine for neighboring countries -what do you think @ClaraIV?

<img width="1330" alt="Screen Shot 2023-06-11 at 4 57 44 PM" src="https://github.com/kartoza/rezoning-2-project/assets/57463392/e15e27ec-9f4a-44e2-a72c-01fa3da49d54">
<img width="1328" alt="Screen Shot 2023-06-11 at 4 56 47 PM" src="https://github.com/kartoza/rezoning-2-project/assets/57463392/2e81b226-b6de-4cf6-88df-7d71c6f4eeb3">

**Comment by ClaraIV** [comment]
I think we can leave it as is for now and see what orher feedback we
receive on the topic, maybe this is indeed good to keep as is.

**Comment by gclapp1** [comment]
Closing this ticket and making note of receiving additional feedback from WBG colleagues on preferences
