### ISSUE TITLE
Investigate the default parameters of the app

### ISSUE THREAD

**Issue by NEDJIMAbelgacem** [kartoza/rezoning-2-project#62]

**Comment by NEDJIMAbelgacem** [comment]
Relates to #40

**Comment by akshay2408** [comment]
Hi @ClaraIV 
I need your help in this.
Could you please explain what needs to be done here as it is not clear to me from comments and title.
Thanks

**Comment by ClaraIV** [comment]
please see ticket 40 linked above, it relates to that - Belgacem created this ticket to further investigate the cases that are presented in ticket #40

**Comment by gclapp1** [comment]
Closing in relation to ticket #40
