### ISSUE TITLE
Toggle issue

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/rezoning-2-project#65]
Issue reported by Clara:

"Perhaps we need a separate ticket for this, but I am trying to document what I see going wrong with the tool in once place, grateful if you can split it to tickets accordingly.
I was testing today OffshoreWind - Curacao to check ticket https://github.com/kartoza/rezoning-2-project/issues/57 and the following happened:

I ran Offshore Wind 50km grid and see results -> all good
I then change grid to 25km and run tool -> results show up but I cannot toggle any of the result layers: Suitable Areas/ LCOE/ Zone Score; I get a symbol when I hover on top of them"

![image](https://github.com/kartoza/rezoning-2-project/assets/90245715/c2bca4f4-8084-42bd-b408-b30312fd116f)

**Comment by ClaraIV** [comment]
I tried with other countries where the tool runs correctly, and the issue with the toggle of layers seems to be fixed;

**Comment by akshay2408** [comment]
@gclapp1 needs to confirm and after that we will move this ticket.

**Comment by gclapp1** [comment]
Have tested multiple countries for all 3 RE options, issue seems resolved. I think I may have been checking the live version accidentally for this ticket. 

Please feel free to close.
