### ISSUE TITLE
Changing zone type and size and getting no zones returned

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/rezoning-2-project#66]
I was testing another ticket for Aruba, and the below happened: I got an error message of NO Zones even if I have suitable areas in the country.
If you want to try to replicate the error:
- select Aruba, Solar and country borders -> run tool -> suitable areas and 1 zone appears
- change selection to 25km2 grid and re-run tool -> this happens

This looks like a new bug, can you kindly create a new ticket for this?
We will close this ticket once the issue is solved

![image](https://user-images.githubusercontent.com/9391517/232781485-5f04d908-f7e2-412d-b21f-d8be57484737.png)

_Originally posted by @ClaraIV in https://github.com/kartoza/rezoning-2-project/issues/43#issuecomment-1513059493_

**Comment by dimasciput** [comment]
@LunaAsefaw this should already fixed right?

**Comment by gclapp1** [comment]
Aruba appears fixed and haven't found this issue for other countries so will close this ticket accordingly.
