### ISSUE TITLE
Clip Regions [Epic 4]

### ISSUE THREAD

**Issue by NEDJIMAbelgacem** [kartoza/rezoning-2-project#7]
### Expectation: 
Clip regional analysis data, which is currently a global layer[.](https://rezoning.energydata.info/)
### Dependencies:
None
### Description:
When selecting a region instead of a country, the current application simply navigates to the regional extent, but provides a global layer which is not clipped or masked accordingly.
### Scope:
The optimal process may depend on existing implementation details.
### Requirements:
Data processing pipeline details and access to vector source processes
### Success Criteria:
Vector features are visibly limited in extent to the selected regional boundaries

**Comment by NEDJIMAbelgacem** [comment]
Relates to https://github.com/kartoza/rezoning-2-project/issues/6
Probably simular aproach

**Comment by NEDJIMAbelgacem** [comment]
# UPDATE: 
There is a huge distiction between this and https://github.com/kartoza/rezoning-2-project/issues/6. 
The current behaviour of the app is that when a region is selected there is nothing specified for regions in the layer request:
For example for a URL requesting tile 5,17,13 of gsa-pvout layer of the country DZD will look like this:
https://d2b8erzy6y494p.cloudfront.net/v1/layers/DZA/solar/gsa-pvout/5/17/13.png?colormap=viridis
But for selecting MENA region for example the request URLs for the same tile 5, 17,13 will look like this:
https://d2b8erzy6y494p.cloudfront.net/v1/layers/gsa-pvout/5/17/13.png?colormap=viridis
Which doesn't contain any country or region code to be used by the backend in order to clip the unnecessary tiles.
This ultimately turns in to the displayed solar power output (gsa-pvout raster) for a region looking like this:

![clip-regions](https://user-images.githubusercontent.com/29183781/209132849-48ffa64a-023d-4197-85e1-7ae1a0b42922.png)

# Potential way to fix it:
- Add necessary bachend endpoints specific for returning tiles (these end points will be responsible for returning empty tiles for areas outside the selected regions)

**Comment by NEDJIMAbelgacem** [comment]
Addressed in https://github.com/worldbank/WB-rezoning-explorer/pull/4 and https://github.com/worldbank/WB-rezoning-explorer-api/pull/4
Ping @ClaraIV , @gclapp1

**Comment by ClaraIV** [comment]
this is not oin staging site yet

**Comment by ClaraIV** [comment]
Please see errors in layer for Black Sea below:

![image](https://user-images.githubusercontent.com/9391517/218753882-f770241d-0e2e-495e-a92d-a6a4fc2a93c9.png)

**Comment by ClaraIV** [comment]
Offshore wind doesn't look right neither for the inland regions, see how Offshore Wind layer is presented in land below:

![image](https://user-images.githubusercontent.com/9391517/218755121-28f33b6e-dccb-48b9-9aba-dc0a10a98d65.png)

**Comment by gclapp1** [comment]
None of the regional level Offshore wind appear to be generating correctly:
- Caribbean, Caspian and Black Sea are difficult to interpret, for other regions certain countries are being excluded or filtered out:
-Eastern and Southern Africa has difficult to understand patchwork of wind speed zones around Madagascar

- MENA
- >Excluded: Israel

- Western and Central Africa
- > Excluded: Sierra Leone, Liberia, Côte d'Ivoire, Nigeria, Gabon, area between Senegal and Cape Verde

**Comment by NEDJIMAbelgacem** [comment]
The script for creating the geometries has some broken parts and I'm currently investigating this problem.
One clue I have is that some countries like russia have some very wide areas which break the creation of cutline (masking) of tiles, but I am yet to apply solution to it.

**Comment by ClaraIV** [comment]
The issue seems to be global for offshore wind - see below the case for Cabo Verde, a small area:



![Image](https://user-images.githubusercontent.com/9391517/225674864-ecd0547e-71ee-4c49-8fa0-265a8e313c9e.png)

**Comment by NEDJIMAbelgacem** [comment]
The artifact of this have been addressed and doesn't appear anymore.

**Comment by ClaraIV** [comment]
@akshay2408 @dimasciput 
Perhaps related or a separate ticket, but the offshore wind layer is not loading properly for all countries - please try Greenland - there is data for the country but it is not displayed in its entirety
![image](https://user-images.githubusercontent.com/9391517/236497197-90fb2c1a-d3b0-41be-b856-76cb07ce07c1.png)

![image](https://user-images.githubusercontent.com/9391517/236497285-413818e0-d05f-450c-8d6e-6875a69861e8.png)

**Comment by gclapp1** [comment]
Looks great, tested all 6 regions and clipping is now consistent with geographic area of interest.

Closing ticket and moving to Accepted.
