### ISSUE TITLE
Grid size issue

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/rezoning-2-project#72]
When our developers were trying to decipher the issues with zones not being generated for some countries (mostly smaller countries), they discovered a bug. The functional requirements say that the zones are: boundaries,  25km<sup>2</sup> and 50km<sup>2</sup>. 
If the grid is 25km<sup>2</sup>, that means the cell size needs to be 5 km by 5 km, and not 25 km by 25 km, which is 625 km<sup>2</sup> and not  25 km<sup>2</sup>. So when this staging site was changed to generate zones of 5 km by 5 km ( 25 km<sup>2</sup>), a few countries that returned suitable areas but no zones (failed 66 and 70) were now generating zones successfully, eg Andorra and Anguilla. However, larger countries take an extremely long time to generate results, for example, Angola took 35 minutes to generate onshore wind results at  25 km<sup>2</sup> grid. When this was investigated against the original rezoning site, Afghantistan returned 933 zones. This means it was generated on a 25 km grid and not 25 km<sup>2</sup> because area for Afghanistan is 652860 km<sup>2</sup>, that divided by 625  km<sup>2</sup> is 1044 zones. If 933 zones were returned on the site, this shows that this was done on a 25 by 25 km grid (625km<sup>2</sup>) and not 5 by 5 km grid ( 25km<sup>2</sup>). 
![image](https://github.com/kartoza/rezoning-2-project/assets/90245715/511a55dc-9172-426b-9dd4-afb51179a435)

Proposed solutions: we keep 625 km<sup>2</sup> 2500  km<sup>2</sup> so the grid lengths are 25km and 50 km each and add another zone for the smaller regions, such as 5 km grid. So the options would be 5 Km (25  km<sup>2</sup>), 25 km (625  km<sup>2</sup>) and 50 km (2500  km<sup>2</sup>)

**Comment by LunaAsefaw** [comment]
@ClaraIV @dimasciput I downloaded the zones geojson files from the original site and calculated the area for them.
Output for 50 km<sup>2</sup>: Area is closer to 2500 km<sup>2</sup> (50 km x 50 km)
![image](https://github.com/kartoza/rezoning-2-project/assets/90245715/20c6cca8-ac07-4b25-b698-ee975d48ded8)

Output for 25 km<sup>2</sup>: Area is closer to 625 km <sup>2</sup> (25 km x 25 km):
![image](https://github.com/kartoza/rezoning-2-project/assets/90245715/5840b3d5-34a6-496d-85a2-5dee9dc34192)

**Comment by ClaraIV** [comment]
Thanks a lot Luna, then it is clear- an oversight on this from our side.
Looking forward to Dima’s assessment of all implications before proceeding
to implementing your suggested solution

**Comment by LunaAsefaw** [comment]
Thanks @ClaraIV 
I will be meeting with Dimas in a few hours to discuss the implications of the new implementation. I will update you immediately after the meeting and we'll finalize the way forward.

**Comment by LunaAsefaw** [comment]
@ClaraIV after discussing we Dimas, we concluded that having four zone sizes is better: Boundary, 5 Km, 25 Km and 50 Km.
However, if countries are larger than an agreed upon area (the specific area to be confirmed), the user will only get the options: Boundary, 25 Km and 50 Km to avoid slow responses and if countries are too small, they only get the options: Boundary, 5 Km and 25 Km, to avoid the error of getting no zones generated when the actual issue is that the country is smaller than grid size.
Dimas said it should not have any negative implications and would not take too long to implement so once we get the thumbs up from you on this approach, we can start.

**Comment by ClaraIV** [comment]
That sounds like a great idea guys, thanks!
Lets please go ahead with it

**Comment by LunaAsefaw** [comment]
@gclapp1 Passed internal testing because countries like US and Cayman Island failed for boundaries but that has been fixed now. 

![Image](https://github.com/kartoza/rezoning-2-project/assets/90245715/c3695f4c-7b0c-4118-8273-5c8408282eac)

Countries that were too small for the 25 km grid have been fixed to only show boundary and 5 km. This was the reason Mayotte failed during one of our sprint meetings but it works now.


![Image](https://github.com/kartoza/rezoning-2-project/assets/90245715/c7b87190-7d0f-41c0-b934-19190aabb4ae)

Countries that are limited to boundary and 5 km still have 25 and 50 Km option for offshore:


![Image](https://github.com/kartoza/rezoning-2-project/assets/90245715/cabf5fd4-da31-4632-b906-716ec8c0fc70)

**Comment by LunaAsefaw** [comment]
![Image](https://github.com/kartoza/rezoning-2-project/assets/90245715/8545cad4-336b-4dbd-98e5-91311df566bd)

**Comment by LunaAsefaw** [comment]
Investigate exclusion of Texas and California

**Comment by gclapp1** [comment]
Looks like Texas and California have been fixed since we last spoke. Thank you, this and original issue have been tested and addressed so closing ticket.
