### ISSUE TITLE
When parameters are changed, contextual layers pop up should close and open when results are generated

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/rezoning-2-project#74]
@akshay2408 this works fine! Can you please also close the Contextual Layers window upon the same change?
Since it is displaying access to results, it should have the same behaviour as the Zone Analysis window

_Originally posted by @ClaraIV in https://github.com/kartoza/rezoning-2-project/issues/59#issuecomment-1551933341_

**Comment by ClaraIV** [comment]
@LunaAsefaw can all the outputs be closed when we change resources? The 2 windows work fine but there is also the Zone Histogram which stays open when I change the resource:
![image](https://github.com/kartoza/rezoning-2-project/assets/9391517/a7cf33b4-f1f9-4c7a-bc42-04a753055197)

**Comment by LunaAsefaw** [comment]
@ClaraIV no problem. 
@dimasciput @akshay2408  please see the comment above.

**Comment by gclapp1** [comment]
Tested for multiple countries and zone sizes found the generated results are cleared when changing resources, works great- closing ticket.
