### ISSUE TITLE
Add feedback form 

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/rezoning-2-project#75]
@akshay2408 during the meeting, Grayson suggested adding a feedback form somewhere else so they don't only view it only after generating zones. If I am not mistaken, the circled area was proposed @gclapp1 
![image](https://github.com/kartoza/rezoning-2-project/assets/90245715/b62a45ee-f319-4795-a056-47faff631f74)

**Comment by akshay2408** [comment]
Hi @ClaraIV @LunaAsefaw Here is the updated UI :
Is it good ?
<img width="1679" alt="Screenshot 2023-05-30 at 4 14 53 PM" src="https://github.com/kartoza/rezoning-2-project/assets/11027786/910cca68-9faf-434c-88b3-8021b43c9bd7">

**Comment by LunaAsefaw** [comment]
@akshay2408 great, thanks! Once it is deployed on the staging site, I will test it and give feedback

**Comment by gclapp1** [comment]
@akshay2408 and @LunaAsefaw 

Thank you for adding the feedback form on the left navigation bar. That is great placement. Would it be possible to have the pop-out bubble have the full blue color border to avoid a white box on a white background?

**Comment by LunaAsefaw** [comment]
@ClaraIV @gclapp1 I just wanted to confirm if this feedback form is an additional feature or meant to replace the old feedback form on the right?

**Comment by ClaraIV** [comment]
@LunaAsefaw this should not replace the feedback form on the right side; this is the response to @gclapp1 's suggestion to have the feedback form also visible when the tool is not ran yet.
Therefore we'll keep it in both places now
