### ISSUE TITLE
Import and Export Icons Need to be Swapped

### ISSUE THREAD

**Issue by dimasciput** [kartoza/rezoning-2-project#77]
**:bug: Describe the bug**

The import and export icons in the UI appear to be mistakenly swapped. The icon that represents 'Import' is currently representing 'Export', and vice versa.

**:bulb: Expected Behavior**

The 'Import' icon should represent the import function and the 'Export' icon should represent the export function. As it stands, their roles are incorrectly switched.

**:camera_flash: Screenshot**

![image](https://github.com/kartoza/rezoning-2-project/assets/1979569/f81acc15-c653-4989-bdd2-0dc922665aee)

**Comment by dimasciput** [comment]
cc @ClaraIV @LunaAsefaw

**Comment by LunaAsefaw** [comment]
@dimasciput Tim and Clara requested that we make it Export then Import in #45

**Comment by dimasciput** [comment]
@LunaAsefaw this issue is about the incorrect icon.

**Comment by LunaAsefaw** [comment]
Oh my apologies, I completely missed that. Thanks!

**Comment by dimasciput** [comment]
The import icon should be an arrow in:
![image](https://github.com/kartoza/rezoning-2-project/assets/1979569/b488a2e0-f04d-41ae-81c3-600273ba73ee)

Export should be arrow out:
![image](https://github.com/kartoza/rezoning-2-project/assets/1979569/56df9845-a0b6-4dc0-9e2c-4edc5d07d319)
