### ISSUE TITLE
Secure GitHub Token Handling 

### ISSUE THREAD

**Issue by dimasciput** [kartoza/rezoning-2-project#78]
### :bug: Describe the Issue

Currently, our GitHub token is being exposed. This poses a significant security risk and should be corrected immediately.

 ###  :bulb: Proposed Solution

We need to create a backend API to handle GitHub feedback transactions. This way, the frontend simply needs to call the backend, protecting our GitHub token from exposure.

 ### :dart: Expected Behavior

The frontend should be able to send and receive necessary data without directly handling the GitHub token. All transactions requiring the GitHub token should be processed in the backend. This way, the GitHub token remains secure and unexposed.

 ### :memo: Additional Context 

This is a critical security issue and needs to be addressed urgently. The current exposure of the GitHub token can lead to unauthorized access and manipulation of our repositories.

 ### :footprints: Steps to Proceed

- Implement a new backend API for GitHub feedback transactions.
- Adjust the frontend to interact with this new API instead of directly using the GitHub token.
- Test thoroughly to ensure security and functionality.

**Comment by dimasciput** [comment]
cc @ClaraIV @LunaAsefaw @akshay2408

**Comment by akshay2408** [comment]
@dimasciput the backend api is done and here is the PR https://github.com/worldbank/WB-rezoning-explorer-api/pull/19
Please check.

**Comment by akshay2408** [comment]
@dimasciput This PR is for Fixes on frontend https://github.com/worldbank/WB-rezoning-explorer/pull/80
please check.
