### ISSUE TITLE
Areas that return very few zones have incorrect visualisation

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/rezoning-2-project#79]
🐛 Describe the bug

The zone score says it is =1 but when you look at what 1 is on the legend, it should be dark blue instead. Similar situation for the second image, still not the correct shade.

💡 Expected behavior

If the zone score value is equal to 1, it should generate a dark blue cell, not a turquoise one (which means zone=0)

📸 Screenshot

![Image](https://github.com/kartoza/rezoning-2-project/assets/90245715/fb2384ec-13ce-4df3-ae31-a8feb453cf10)

![Image](https://github.com/kartoza/rezoning-2-project/assets/90245715/eb65a82c-40f7-4e79-87a3-b15c15280d12)

**Comment by dimasciput** [comment]
@akshay2408 let me work on this one

**Comment by gclapp1** [comment]
Tested for eight Pacific Island countries and four small European countries- all worked so closing ticket.
