### ISSUE TITLE
Dateline [Epic 5 (Discovery)]

### ISSUE THREAD

**Issue by NEDJIMAbelgacem** [kartoza/rezoning-2-project#8]
Note that discovery tasks will be completed by order of priority in line with discovery task requirements[.](https://rezoning.energydata.info/) Discovery may include documentation and/ or implementation of feature design.
### Expectation: 
Include countries with boundaries crossing the dateline
### Priority: 
High
### Dependencies:
None
### Description:
Include USA and remaining countries/islands that have been removed from v.1.0 due to data issues arising from boundaries crossing the dateline
### Scope:
The scope of this process will depend on the results of the discovery process.
### Requirements:
None
### Success Criteria:
Inclusion of the countries currently excluded from the application

**Comment by timlinux** [comment]
Duplicates #16
