### ISSUE TITLE
Accessibility to countries with accented characters

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/rezoning-2-project#82]
🐛 Describe the bug
Countries with special characters are difficult to search for on the site, they are moved to the back of the list. For example: Côte d'Ivoire and São Tomé and Príncipe

💡 Expected behavior
Côte d'Ivoire and São Tomé and Príncipe should be easily discoverable.

![Image](https://github.com/kartoza/rezoning-2-project/assets/90245715/dd88bf03-db9f-4f2d-b465-0da7b287cc4d)

![Image](https://github.com/kartoza/rezoning-2-project/assets/90245715/c63386f8-62f4-46ff-8fff-93d679e132c0)

**Comment by gclapp1** [comment]
Tested, closing.
