### ISSUE TITLE
Interrupted pop-up

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/rezoning-2-project#83]
![Image](https://github.com/kartoza/rezoning-2-project/assets/90245715/e4186f6a-54bd-47df-9ade-4a6f27b64a46)

**Comment by LunaAsefaw** [comment]
No, a PR has been made for this issue but has not been merged. Clara suggested that the histogram also disappears when parameters are changed but in doing that, the histogram disappeared completed but I have asked Akshay to fix this error, which he did and is just waiting for the PR to be merged. Hence the issue (#74) relating to this hasn't been moved to 'Passed internal testing'

**Comment by dimasciput** [comment]
The PR has been merged and is now ready for the client to test. @LunaAsefaw, could you also check this, please?

**Comment by LunaAsefaw** [comment]
I checked this and moved it to "passed internal testing" @dimasciput. The client will move it once they test and are happy
