### ISSUE TITLE
Data Rendering Issues [Epic 5 (Discovery)]

### ISSUE THREAD

**Issue by NEDJIMAbelgacem** [kartoza/rezoning-2-project#9]
Note that discovery tasks will be completed by order of priority in line with discovery task requirements[.](https://rezoning.energydata.info/) Discovery may include documentation and/ or implementation of feature design.

![data-rendering-issues](https://user-images.githubusercontent.com/29183781/203070247-2c0831af-9fca-46e8-bd66-64b10df3d464.png)
### Expectation:
Fix rendering issues with some layers caused by data inconsistencies
### Priority:
High
### Dependencies:
Rendering issues should be resolved with some layers that are caused by data inconsistencies, e.g. Offshore Wind – Argentina.
### Description:
Description
### Scope:
The scope of this process will depend on the results of the discovery process.
### Requirements:
A list of affected layers, and data processing pipeline details
### Success Criteria:
All affected layers are rendered effectively and consistently

**Comment by ClaraIV** [comment]
this looks good!

**Comment by NEDJIMAbelgacem** [comment]
The issue discussed last meeting has been addressed. I found some faulty layers minimum values that were 0 and now are updated to higher values (calculated from the datasets themselves)
